In [51]:
import torch
import numpy as np
from torch import nn
import random
import math

In [52]:
import json
data = json.loads(open("dataset_1.json").read())
X_train = np.array(data["X"]).astype(np.double)
Y_train = np.array(data["Y"]).astype(np.double)

In [53]:
class BG(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(3, 3)
        self.act = nn.ReLU()
        self.l2 = nn.Linear(3, 1)
        self.act2 = nn.ReLU()
    
    def forward(self, x):
        x = self.l1(x)
        x = self.act(x)
        x = self.l2(x)
        x = self.act2(x)
        return x
model = BG()

In [68]:
loss_function = nn.L1Loss()
optim = torch.optim.Adam(model.parameters())
for i in range(1000):
    samp = math.floor(random.random()*len(X_train))
    print(samp)
    input = torch.tensor(X_train[samp]).float()
    target = torch.tensor(Y_train[samp]).long()
    optim.zero_grad()
    guess = model(input)
    #print(guess)
    print(guess, target)
    loss = loss_function(guess, target)
    loss.backward()
    optim.step()
    print(loss.item())

13
tensor([0.4355], grad_fn=<ReluBackward0>) tensor(0)
0.4354897439479828
42
tensor([0.4786], grad_fn=<ReluBackward0>) tensor(1)
0.5213945508003235
22
tensor([0.5134], grad_fn=<ReluBackward0>) tensor(1)
0.48656177520751953
16
tensor([0.5194], grad_fn=<ReluBackward0>) tensor(1)
0.48063743114471436
43
tensor([0.5131], grad_fn=<ReluBackward0>) tensor(1)
0.48687928915023804
24
tensor([0.4753], grad_fn=<ReluBackward0>) tensor(1)
0.524696946144104
29
tensor([0.4580], grad_fn=<ReluBackward0>) tensor(1)
0.5420188903808594
33
tensor([0.4987], grad_fn=<ReluBackward0>) tensor(0)
0.49873411655426025
17
tensor([0.4440], grad_fn=<ReluBackward0>) tensor(0)
0.44397667050361633
26
tensor([0.4845], grad_fn=<ReluBackward0>) tensor(1)
0.515457034111023
38
tensor([0.4407], grad_fn=<ReluBackward0>) tensor(0)
0.44068312644958496
37
tensor([0.4555], grad_fn=<ReluBackward0>) tensor(0)
0.4555385708808899
6
tensor([0.4552], grad_fn=<ReluBackward0>) tensor(0)
0.4552164077758789
37
tensor([0.4556], grad_fn=<ReluBa