In [9]:
import numpy as np
import matplotlib.pyplot as plt

In [87]:
class Matrix:
    def __init__(self, cols, rows):
        self.matrix = np.zeros((cols, rows))

    def mirror(self):
        return Matrix(len(self.matrix[0]), len(self.matrix))

    def set(self, mat):
        self.matrix = mat
        return self
    
    def __mul__(self, other):
        res = self.mirror()
        if isinstance(other, int) or isinstance(other, float):
            for y in range(len(self.matrix)):
                for x in range(len(self.matrix[0])):
                    res.matrix[y][x] = self.matrix[y][x] * other
        return res

    def __add__(self, other):
        res = self.mirror()
        if isinstance(other, int) or isinstance(other, float):
            for y in range(len(self.matrix)):
                for x in range(len(self.matrix[0])):
                    res.matrix[y][x] = self.matrix[y][x] + other
        elif isinstance(other, Matrix):
            for y in range(len(self.matrix)):
                for x in range(len(self.matrix[0])):
                    res.matrix[y][x] = self.matrix[y][x] + other.matrix[y][x]
        return res


a = Matrix(2, 2)
b = Matrix(2, 2)
a.matrix
a = a + 10
a = a * 10
a.matrix

array([[100., 100.],
       [100., 100.]])

In [102]:
c = np.floor(np.random.rand(1, 4)*10)
d = np.floor(np.random.rand(4, 3)*10)
c, d

(array([[4., 8., 7., 3.]]),
 array([[0., 3., 0.],
        [2., 7., 4.],
        [3., 9., 6.],
        [9., 0., 5.]]))

In [103]:
np.dot(c, d)

array([[ 64., 131.,  89.]])

In [196]:
# neural network test

layers = [2, 8, 10, 1]
weights = []

# activation
sig = lambda x: 1/(1+(np.e**(-x)))

# generate weight matrix
for i in range(1, len(layers)):
    current = np.random.rand(layers[i-1], layers[i]) * 2 - 1
    weights.append(current)

#forward
input = np.floor(np.random.rand(1, 2)*10)
for w in weights:
    input = input @ w
    for i in range(len(input[0])):
        input[0][i] = sig(input[0][i])

input

array([[0.85398451]])